### ISSUE TITLE
inverted mode for picture

### ISSUE THREAD

**Issue by trungng2006** [sissilab/obsidian-image-toolkit#1]
Could you please implement the invert color for dark mode?
Its something like this: https://github.com/ozntel/oz-image-in-editor-obsidian/issues/32

**Comment by sissilab** [comment]
Did you mean that you can view an image in the invert color on the popup layer?
![image](https://user-images.githubusercontent.com/82884158/131282519-3968d86e-f500-4a0a-b7d8-7dd5a253c184.png)

**Comment by sissilab** [comment]
> Could you please implement the invert color for dark mode?
> Its something like this: [ozntel/oz-image-in-editor-obsidian#32](https://github.com/ozntel/oz-image-in-editor-obsidian/issues/32)

Did you mean that you can view an image in the invert color on the popup layer?
![bird](https://user-images.githubusercontent.com/82884158/131282841-07a25609-f991-4e08-add9-abd8db4f68d4.png)

**Comment by trungng2006** [comment]
Yes, this is what i mean! :D

**Comment by sissilab** [comment]
> Yes, this is what i mean! :D

You'll see it in the next version. ^v^

**Comment by trungng2006** [comment]
Thank you so much!!!

**Comment by sissilab** [comment]
> Thank you so much!!!

Hi, I have added some new features, including yours. See it: https://github.com/sissilab/obsidian-image-toolkit/releases.
You can give me a feedback if there is any problem.

**Comment by trungng2006** [comment]
Thank you!
Will do! :D
