### ISSUE TITLE
How can restore files to their original location ???

### ISSUE THREAD

**Issue by ajiasha** [sissilab/obsidian-image-toolkit#101]
So, after I performed the "Clear Unused Attachments" operation, I accidentally deleted a large number of useful data files. How can I restore these files to their original location? Right now, they are all in the .trash directory.

<img width="917" alt="image" src="https://github.com/sissilab/obsidian-image-toolkit/assets/106713956/c71bb25f-0b73-4d90-911a-a41316beec80">

**Comment by sissilab** [comment]
> So, after I performed the "Clear Unused Attachments" operation,

The operation isn't related to this plugin. You should find for it in other plugins, like `Clear Unused Images`.
