### ISSUE TITLE
Can't open images when inside callouts

### ISSUE THREAD

**Issue by itsonlyjames** [sissilab/obsidian-image-toolkit#113]
Image inside callout:

<img width="882" alt="Screenshot 2024-06-29 at 20 41 28" src="https://github.com/sissilab/obsidian-image-toolkit/assets/6904599/f77e4143-b769-497f-8a4d-02919553e50c">

Clicked (it squishes). When using a mouse I can get it to work some times but it's random

<img width="776" alt="Screenshot 2024-06-29 at 20 41 31" src="https://github.com/sissilab/obsidian-image-toolkit/assets/6904599/63e434c7-d704-4e7c-a43d-e6a26e2e024c">

**Comment by sissilab** [comment]
@itsonlyjames  Thanks for the feedback on this issue. I'm trying to reproduce it, and it seems that this plugin can still work but only display the source code of that Callout block in Preview Mode. I haven't encountered any squished images and so could you please provide more details about that if you still got that problem.

**Comment by itsonlyjames** [comment]
@sissilab Interestingly, I no longer have any issues with opening an image inside a callout, whether by an update or other means I'm unsure (maybe I caused the issue myself in my vault with custom CSS or something). 
Anyway, when opening the image inside the callout, it does make active the callout, and as such can interupt the flow of the page. I wonder if it's possible to add a `preventDefault` or something to stop "editing" the callout, like it would if you click on any part of the callout in edit mode. 
Behaviour is different depending on whether you click out of the image, or press escape. Both scenarios are encompassed in the below gif, respectively:
![Jul-02-2024 11-03-00](https://github.com/sissilab/obsidian-image-toolkit/assets/6904599/b694b120-8287-46d9-9fb4-76bb181f7dc7)

**Comment by itsonlyjames** [comment]
@sissilab, I will close this issue as it is fixed and will look into the other request I made in a seperate PR. Cheers
