### ISSUE TITLE
Image Copy-Pasting

### ISSUE THREAD

**Issue by Live-AG** [sissilab/obsidian-image-toolkit#12]
It would be great if would be possible to copy image to buffer (and in fullscreen mode too) (for example: by right mouse click), to past to another place or document, or letter for exemple.

**Comment by sissilab** [comment]
> It would be great if would be possible to copy image to buffer (and in fullscreen mode too) (for example: by right mouse click), to past to another place or document, or letter for exemple.

Hi, version 0.3.5 has provided copying an image, and you can paste it to any document. 
As to fullscreen mode, the intent of design is just viewing an image without other operation.

**Comment by Live-AG** [comment]
Thank you)
