### ISSUE TITLE
Previous and next image

### ISSUE THREAD

**Issue by javiavid** [sissilab/obsidian-image-toolkit#13]
Your plugin is very useful, but I wanted to propose an improvement.

It is very common to have several images in a document,
Is a shortcut possible to change to the previous and next image without leaving the enlarged image?

**Comment by sissilab** [comment]
> Your plugin is very useful, but I wanted to propose an improvement.
> 
> It is very common to have several images in a document,
> Is a shortcut possible to change to the previous and next image without leaving the enlarged image?

Thanks, and I have been thinking about how to implement it in a perfect way. I'll add this feature in the future, and maybe a little late.

**Comment by sissilab** [comment]
> Your plugin is very useful, but I wanted to propose an improvement.
> 
> It is very common to have several images in a document,
> Is a shortcut possible to change to the previous and next image without leaving the enlarged image?

Thanks, and I have been thinking about how to implement it in a perfect way. I'll add this feature in the future, and maybe a little late.

**Comment by cansar** [comment]
+1 I LOVE this plugin and this would make it even better. It's probably the thing I most miss in Obsidian.

**Comment by accept82** [comment]
I fully support your idea of ​​flipping through images if possible if there are several images in your notes! And if you also add my request to your idea, it will be very convenient, that is, after scrolling through the images, you exit the plug-in and the image on which you stopped is highlighted. Here is a link to my feature request: https://github.com/sissilab/obsidian-image-toolkit/issues/27

**Comment by javiavid** [comment]
It´s a great idea @accept82.
I hope @sissilab can make these changes.

**Comment by keerah** [comment]
+101 !

**Comment by sissilab** [comment]
@javiavid @cansar @accept82 @keerah 
Hi, finally, finally, finally...
The plugin verion has upgrade to v1.0.1. 
You can preview all the images of the editor area at the bottom of the popup layer, and you can switch them. But the default setting is false, you need to turn it on.

**Comment by javiavid** [comment]
It's great to be able to see all the images at the bottom! Thanks
Is it possible to change the image with a shortcut?

**Comment by sissilab** [comment]
> 

Did you mean that you can  swtich to the last/next image by arrow left/right?

**Comment by cansar** [comment]
This is incredible! I had to restart to make it work but it works perfectly now!! Such a big deal.

I agree that having either an Obsidian command for prev/next so that one can assign shortcuts would be great, but honestly using the back/forward arrows by default would be even better IMO if that's reasonable to do.

Thank you so much for your work!

P.s. this works in both Live Preview and Reader for me, not sure why the documentation says Reader only...

**Comment by keerah** [comment]
Wow, thanks for implementing this, but would really love to have the shortucts

**Comment by cklaffer** [comment]
> > 
> 
> Did you mean that you can switch to the last/next image by arrow left/right?

Yes, please, that would be perfect. I don't need to move the image with the arrow keys, I have a mouse ;-) Or make it Ctrl/Cmd + Arrow to move it, but arrow only to switch images. 

Also, Ctrl/Cmd+mousewheel to change images would also be perfect.

Thanks for the wonderful work!

**Comment by sissilab** [comment]
@javiavid @cansar @keerah @cklaffer 
Hi all, I've added shortcuts for switching the image, you can see the hotkey settings.
Please upgrade to v1.2.0. Thanks for your support!

**Comment by sissilab** [comment]
@javiavid @cansar @keerah @cklaffer 
Hi all, I've added shortcuts for switching the image, you can see the hotkey settings.
Please upgrade to v1.2.0. Thanks for your support!
