### ISSUE TITLE
Center image on the fullscreen view.

### ISSUE THREAD

**Issue by ham1204** [sissilab/obsidian-image-toolkit#14]
Thanks for the great plugin.
The recent update makes it very easy to use.
It would be perfect if, when in fullscreen view, the vertical image would be centered instead of left-aligned!

**Comment by sissilab** [comment]
> Thanks for the great plugin.
> The recent update makes it very easy to use.
> It would be perfect if, when in fullscreen view, the vertical image would be centered instead of left-aligned!

Thanks for your reply, I'll check it.

**Comment by sissilab** [comment]
Hi, I have solved itl
Please update v0.4.0: https://github.com/sissilab/obsidian-image-toolkit/releases/tag/0.4.0.
