### ISSUE TITLE
Fix fullscreen mode

### ISSUE THREAD

**Issue by accept82** [sissilab/obsidian-image-toolkit#15]
1. In the full-screen view mode, the cursor must be displayed. At the moment it is not there - this is very inconvenient - it is not clear what is happening - there is no control - all programs have a cursor!
2. In the full-screen view, the windows control panel does not close - and, in fact, the meaning of full-screen view is lost.

Here is an example of how it works in other programs and how it is currently implemented in this plugin.
Please make it a handy tool
![12-09-2021_20-57_s6088](https://user-images.githubusercontent.com/90281362/132997943-de2b12b3-ed3c-4346-ae68-5ee742387d28.gif)

**Comment by sissilab** [comment]
> 1. In the full-screen view mode, the cursor must be displayed. At the moment it is not there - this is very inconvenient - it is not clear what is happening - there is no control - all programs have a cursor!
> 2. In the full-screen view, the windows control panel does not close - and, in fact, the meaning of full-screen view is lost.


Thank you very much for your suggestion! 
1. Done with the cursor. You will see it in the next version.
2. The size of the image in full-screen mode depends on the size of the interface of the Obsidian, so you can see the windows control panel in full-screen mode. I haven't yet found a proper way to improve it.

**Comment by accept82** [comment]
Good day! Thanks for the information! If you can find a way to display it in full screen mode, regardless of whether the application is switched to full screen mode or not, that will be just great!
Thanks for your hard work! and I will wait for a new release
