### ISSUE TITLE
Images get distorted with some advanced image layouts

### ISSUE THREAD

**Issue by danebace** [sissilab/obsidian-image-toolkit#16]
Hey,

When clicking on Images with definitions like this
![[image.png|-grid]]  ![[image.png|-left]] 
 they get distorted (flated).
 
 You can try on ITS-theme where they have these advanced options for image display.
 
It would be great if images selected from a grid looked normal
https://user-images.githubusercontent.com/73532672/133224558-fd1200f1-e1e4-4032-a3a4-c21ccb6b3963.mp4

**Comment by sissilab** [comment]
> Hey,
> 
> When clicking on Images with definitions like this
> ![[image.png|-grid]] ![[image.png|-left]]
> they get distorted (flated).
> 
> You can try on ITS-theme where they have these advanced options for image display.
> 
> It would be great if images selected from a grid looked normal
> https://user-images.githubusercontent.com/73532672/133224558-fd1200f1-e1e4-4032-a3a4-c21ccb6b3963.mp4

@danebace  Thanks for your feedback, I've fixed it in the latest version. You can update to v0.4.0:  https://github.com/sissilab/obsidian-image-toolkit/releases/tag/0.4.0.

There're many Obsidian themes, and some of them may affect the css styles.
I'm trying to find the problem out and fix it.
