### ISSUE TITLE
图片不能正常工作

### ISSUE THREAD

**Issue by VinciYan** [sissilab/obsidian-image-toolkit#18]
```
<div class="modal" style="height: 80%; width: 40%;">
    <div class="modal-close-button"></div>
    <div class="modal-title">2014 - 22</div>
    <div class="modal-content sr-modal-content" id="sr-flashcard-view" style="position: relative; height: 92%;">
        <div class="sr-link">Edit Later</div>
        <div class="sr-link" style="float: right; display: none;">Reset card's progress</div>
        <div id="sr-context"></div>
        <div class="div" id="sr-flashcard-view">
            <p><span alt="....../附件/Pasted image 20210918090030.png"
                    src="....../附件/Pasted image 20210918090030.png"
                    class="internal-embed image-embed is-loaded">
                    <img src="app://local/......Pasted%20image%2020210918090030.png?1631926830367"
                        width="100%" alt="....../Pasted image 20210918090030.png"></span></p>
        </div>
        <div class="sr-response" style="display: none;"><button id="sr-hard-btn">Hard - 1 days</button><button
                id="sr-good-btn">Good - 2.5 days</button><button id="sr-easy-btn">Easy - 3.5 days</button></div>
        <div id="sr-show-answer" style="display: initial;">Show Answer</div>
    </div>
</div>
```

上面的代码是使用obsidian-spaced-repetition-1.6.2时产生的。

使用obsidian-spaced-repetition-1.6.2+obsidian-image-toolkit-0.35时，上面图片是能正常工作；使用obsidian-spaced-repetition-1.6.2+obsidian-image-toolkit-0.40，上面的图片不能正常工作

![image](https://github.com/VinciYan/test/blob/main/testimage.gif)

**Comment by sissilab** [comment]
> 使用obsidian-spaced-repetition-1.6.2+obsidian-image-toolkit-0.35时，上面图片是能正常工作；使用obsidian-spaced-repetition-1.6.2+obsidian-image-toolkit-0.40，上面的图片不能正常工作

估计是因为在 v0.4.0 中增加了点击图片的限制，从而导致该问题，麻烦提供下截图以便排查问题。
后面我也可以考虑增加“全局”模式的设置，这样 Obsidian 全局只要包含有图片标签的都可以被点击预览。

**Comment by VinciYan** [comment]
![test](https://github.com/VinciYan/test/blob/main/testimg.gif)

> > 使用obsidian-spaced-repetition-1.6.2+obsidian-image-toolkit-0.35时，上面图片是能正常工作；使用obsidian-spaced-repetition-1.6.2+obsidian-image-toolkit-0.40，上面的图片不能正常工作
> 
> 估计是因为在 v0.4.0 中增加了点击图片的限制，从而导致该问题，麻烦提供下截图以便排查问题。
> 后面我也可以考虑增加“全局”模式的设置，这样 Obsidian 全局只要包含有图片标签的都可以被点击预览。

**Comment by sissilab** [comment]
> ![image](https://github.com/VinciYan/test/blob/main/testimage.gif)

好的，多谢反馈，我会尽快完善这种情况。

**Comment by sissilab** [comment]
您好，我已经发布最新版本 [v0.4.2](https://github.com/sissilab/obsidian-image-toolkit/releases/tag/0.4.2)，您可以更新后尝试下是否有解决您的问题。
若有问题，可随时反馈！
