### ISSUE TITLE
Invert mode as default for [[pic|#invert]]

### ISSUE THREAD

**Issue by trungng2006** [sissilab/obsidian-image-toolkit#19]
When the picture is zoom in, the color always revert to true color, even when the link is inverted mode ([[pic|#invert]])
This only happen after the new update i think, it was fine before.

Could you please help check if it is possible to let the user specify the default color mode of the zoomed in pic?

Related: https://github.com/sissilab/obsidian-image-toolkit/issues/1

**Comment by sissilab** [comment]
> When the picture is zoom in, the color always revert to true color, even when the link is inverted mode ([[pic|#invert]])
> This only happen after the new update i think, it was fine before.
> 
> Could you please help check if it is possible to let the user specify the default color mode of the zoomed in pic?
> 
> Related: #1

Thanks for your feedback, I'll check it.

**Comment by sissilab** [comment]
Hi, I have fixed it in v0.4.2. Please see: https://github.com/sissilab/obsidian-image-toolkit/releases/tag/0.4.2.
You can contact me if you get any problem. ^v^

**Comment by trungng2006** [comment]
Its working now!!!
Thank you so much!!!
