### ISSUE TITLE
[Feature Request] Navigate in a zoomed Image 

### ISSUE THREAD

**Issue by FelipeRearden** [sissilab/obsidian-image-toolkit#2]
Hello, @sissilab and @ForThe77  ! 

Thanks for this plug-in :) 

My FR is to have the possibility to navigate in a image that is zoomed. 

Example: This is a image of a infographic that has a lot of information:
![75A66069-E382-4269-ACB8-DA40B9CC07B5](https://user-images.githubusercontent.com/85180696/131253380-9c3728ad-9f2f-46fb-be7e-545ba3521557.png)

When you use the plug-in to zoom the image I can’t `navigate` from the other side of the image. I’m stuck at the top-left region of the image. (5. Text Mining/NPL -> Orange)

**My suggestion is using the keyboard arrows (top,bottom, right, left) to navigate in the image after zoom :)**

Thanks for this plug-in. Let me know if you need additional information.

Have a great day!

**Comment by sissilab** [comment]
> Hello, @sissilab and @ForThe77 !
> 
> Thanks for this plug-in :)
> 
> My FR is to have the possibility to navigate in a image that is zoomed.
> 
> Example: This is a image of a infographic that has a lot of information:
> ![75A66069-E382-4269-ACB8-DA40B9CC07B5](https://user-images.githubusercontent.com/85180696/131253380-9c3728ad-9f2f-46fb-be7e-545ba3521557.png)
> 
> When you use the plug-in to zoom the image I can’t `navigate` from the other side of the image. I’m stuck at the top-left region of the image. (5. Text Mining/NPL -> Orange)
> 
> **My suggestion is using the keyboard arrows (top,bottom, right, left) to navigate in the image after zoom :)**
> 
> Thanks for this plug-in. Let me know if you need additional information.
> 
> Have a great day!

Hi, zoom an image according to your mouse's position?

![zoom](https://user-images.githubusercontent.com/82884158/131334414-78d2181f-c26f-40f1-9a72-b80b442fbaba.gif)

**Comment by sissilab** [comment]
> Hello, @sissilab and @ForThe77 !
> 
> Thanks for this plug-in :)
> 
> My FR is to have the possibility to navigate in a image that is zoomed.
> 
> Example: This is a image of a infographic that has a lot of information:
> ![75A66069-E382-4269-ACB8-DA40B9CC07B5](https://user-images.githubusercontent.com/85180696/131253380-9c3728ad-9f2f-46fb-be7e-545ba3521557.png)
> 
> When you use the plug-in to zoom the image I can’t `navigate` from the other side of the image. I’m stuck at the top-left region of the image. (5. Text Mining/NPL -> Orange)
> 
> **My suggestion is using the keyboard arrows (top,bottom, right, left) to navigate in the image after zoom :)**
> 
> Thanks for this plug-in. Let me know if you need additional information.
> 
> Have a great day!

Hi, zoom an image by your mouse's postion. Is that what you want?
![zoom](https://user-images.githubusercontent.com/82884158/131334735-626f5505-b359-4f76-96d6-ad21ff5f6c75.gif)

**Comment by FelipeRearden** [comment]
Hello @sissilab !!!!

This is not what I was meant but its a great additional feature :)

What I am requesting is the ability to “walk” in a image that is with zoom (200% for example) using the keyboard arrow keys.

Let’s use my image for example: 
- After zoom I only can se the orange location (5. Text Mining/NPL);
- Then I want to walk to the pink area (7. Big Data) without changing the zoom previous applied 
- My suggestion is using the arrow from keyboard to “walk” from orange to pink without losing the zoom 

:)

**Comment by sissilab** [comment]
> Hello @sissilab !!!!
> 
> This is not what I was meant but its a great additional feature :)
> 
> What I am requesting is the ability to “walk” in a image that is with zoom (200% for example) using the keyboard arrow keys.
> 
> Let’s use my image for example:
> 
> * After zoom I only can se the orange location (5. Text Mining/NPL);
> * Then I want to walk to the pink area (7. Big Data) without changing the zoom previous applied
> * My suggestion is using the arrows (right,left, top. Bottom) from keyboard to “walk” from orange to pink without losing the zoom
> 
> :)

I think you want to move the image after zoom. 
In fact, you can move the image by mouse now. 
And you wanna more moving operations through keyboard (right,left, top. Bottom)?

**Comment by FelipeRearden** [comment]
Yes :) you are right would be amazing to move the image with keyboard :)

**Comment by sissilab** [comment]
> Yes @sissilab :) you are right.
> 
> would be amazing to move the image with keyboard :)

Hi, I have added some new features, including yours. See it: https://github.com/sissilab/obsidian-image-toolkit/releases.

**Comment by FelipeRearden** [comment]
Hello @sissilab !!!

Thank you so much for this feature. Tested the new release and I loved all the new features :)

**I just wanna make a little comment: is it possible to increase a little bit the speed when moving with arrow keys ?**
- It’s very good the way that is now, but I just think if it was a little bit faster, would be better :)

Have a great day !!!!!!

**Comment by sissilab** [comment]
> Hello @sissilab !!!
> 
> Thank you so much for this feature. Tested the new release and I loved all the new features :)
> 
> **I just wanna make a little comment: is it possible to increase a little bit the speed when moving with arrow keys ?**
> 
> * It’s very good the way that is now, but I just think if it was a little bit faster, would be better :)
> 
> Have a great day !!!!!!

Thanks for you feedback. I'll think about providing speed setting in the future.

**Comment by FelipeRearden** [comment]
@sissilab , thank you so much for your reply :)

**Comment by FelipeRearden** [comment]
Hello @sissilab !!!!

I just updated to 0.4.0 and I just wanna say THANK YOU SO MUCH for new features. The new speed setting is just what I need 🎉🎉🎉

> Acknowledge
> Thank you very much for your suggestions, and 'll try my best to make this plug-in better.

We have to say thank you for listen our FR and for being so kind to our community :)
- I'm so happy to see how this plug-in is becoming so powerful since the first release!!!!!

I wish you a fantastic day!!!!!
