### ISSUE TITLE
0.4.2 没有发布

### ISSUE THREAD

**Issue by Borber** [sissilab/obsidian-image-toolkit#20]
只更新了代码, 但是没有发版

**Comment by sissilab** [comment]
> 只更新了代码, 但是没有发版

你速度真快。。。我刚操作完毕，v0.4.2 已经发布了。

**Comment by Borber** [comment]
> > 只更新了代码, 但是没有发版
> 
> 你速度真快。。。我刚操作完毕，v0.4.2 已经发布了。

嘿嘿嘿
