### ISSUE TITLE
emoji/icons displaying centre screen in preview - undesirable?

### ISSUE THREAD

**Issue by jroachgit** [sissilab/obsidian-image-toolkit#22]
Hi!

My emojis/icons (associated with task creation/done) are showing like this:

![image](https://user-images.githubusercontent.com/35711815/139096290-972d5633-419f-4b96-9b3b-0d107807d282.png)

Is this intended?
Is it undesirable?

**Comment by sissilab** [comment]
> My emojis/icons (associated with task creation/done) are showing like this:
> Is this intended? Is it undesirable?

Hi, please let me know more details if you still have this problem now.

**Comment by sissilab** [comment]
Close for now. It will be reopened if you still have the problem.
