### ISSUE TITLE
Stop plugin from working in Themes "store"

### ISSUE THREAD

**Issue by firinael** [sissilab/obsidian-image-toolkit#23]
The "store" already has a "click to enlarge" feature, so this plugin working in it is a bit annoying.

**Comment by accept82** [comment]
This is the best plugin I've seen, great image handling, zooming ability and full screen mode make it a leader in this segment! You can always disable the plugin if it doesn't suit you.

**Comment by accept82** [comment]
I use the Minimal Theme and I was also annoyed by the twitching when the plugin was triggered. I wrote to the theme developer and they quickly implemented the function in the Style Settings plugin (the function turns off the standard image enlargement in the theme) Now everything works as it should and I am very happy. Maybe this will help you too.
![17-11-2021_23-45_s8765](https://user-images.githubusercontent.com/90281362/142279613-de9367ec-6d39-477f-8a28-4a3f407b84e0.png)
