### ISSUE TITLE
Outlining the image after exiting the preview

### ISSUE THREAD

**Issue by accept82** [sissilab/obsidian-image-toolkit#27]
It would be nice if you add a function to highlight the previewed image that is triggered after exiting the preview mode. This is especially useful when there are many images in a note! And it is very desirable that the stroke color be configured in the plugin (relevant for different themes)
![17-11-2021_23-28_s8764](https://user-images.githubusercontent.com/90281362/142278932-6efa2f34-0d96-44bd-b894-00f5b0755196.png)

**Comment by javiavid** [comment]
+1

**Comment by sissilab** [comment]
> It would be nice if you add a function to highlight the previewed image that is triggered after exiting the preview mode. This is especially useful when there are many images in a note! And it is very desirable that the stroke color be configured in the plugin (relevant for different themes)

Thanks for your suggestion! I'll work on it.

**Comment by accept82** [comment]
Thank you for your reply, I will look forward to your new release.

**Comment by sissilab** [comment]
@accept82  Hi, I've added this feature on v0.5.0,  and you can upgrade now.

**Comment by accept82** [comment]
Everything is just super! I am very grateful to you for your work!
