### ISSUE TITLE
Issues with Live Preview

### ISSUE THREAD

**Issue by brimwats** [sissilab/obsidian-image-toolkit#28]
Image toolkit (I'm pretty sure) misaligns an image caption in Live Preview Mode

![image](https://user-images.githubusercontent.com/49103046/142718263-1e686bde-9284-4549-a82e-95385001f7aa.png)
![image](https://user-images.githubusercontent.com/49103046/142718264-2a960541-2b85-4577-8d67-e57c05288d84.png)

**Comment by sissilab** [comment]
> Image toolkit (I'm pretty sure) misaligns an image caption in Live Preview Mode

Sorry, I don't get it. My plugin cannot preview in edit mode.
Could you please provide more information?

**Comment by sissilab** [comment]
Close for now. It will be reopened if you still have the problem.
