### ISSUE TITLE
Move to separate setting of numerical display of image scale

### ISSUE THREAD

**Issue by accept82** [sissilab/obsidian-image-toolkit#29]
Is it possible to somehow transfer the numerical display of the scale on the image to a separate setting. For those who need it, they can enable this setting. For me this displaying the zoom number is overkil
![25-11-2021_23-17_s9364](https://user-images.githubusercontent.com/90281362/143496905-da8114ab-9da8-441b-a4e2-c83ca070e479.png)
l

**Comment by sissilab** [comment]
Hi, I've added this feature on v0.5.0,  and you can upgrade now.

**Comment by accept82** [comment]
Many thanks! The updated version shows that a great job has been done! Everything works great, I am very happy with your plugin. For me, he is number 1 in my work! Thank you for developing it!
