### ISSUE TITLE
[SUGGESTION] Clicking outside the image should close it

### ISSUE THREAD

**Issue by firinael** [sissilab/obsidian-image-toolkit#3]
Most everything, when you click on the faded background outside the image, closes the image view. For quality of life, I think clicking outside the image itself should close the plugin view.

![image](https://user-images.githubusercontent.com/67032657/131264217-6f917344-4c33-4d9b-bb61-8a97037a8066.png)

All of the darkened area around the image that does not have a button should work as the X button.

**Comment by firinael** [comment]
Also miscellaneous question but is it possible to alter the bottom icons without losing functionality?

**Comment by sissilab** [comment]
> Most everything, when you click on the faded background outside the image, closes the image view. For quality of life, I think clicking outside the image itself should close the plugin view.
> 
> ![image](https://user-images.githubusercontent.com/67032657/131264217-6f917344-4c33-4d9b-bb61-8a97037a8066.png)
> 
> All of the darkened area around the image that does not have a button should work as the X button.

Thx for your suggestion, I'll think about it.

**Comment by sissilab** [comment]
> Also miscellaneous question but is it possible to alter the bottom icons without losing functionality?

Hi, do you think those icons aren't pretty? ^v^ 
The plug-in can provide setting icon by yourself?

**Comment by firinael** [comment]
> Hi, do you think those icons aren't pretty? ^v^

They're a bit pixelated on my end, not sure why. Not ugly, just low-res. Maybe switching the icons to SVGs would do the trick? It'd be something you'd probably be able to do quite easily on your end.

> The plug-in can provide setting icon by yourself?

I'm sorry, I didn't understand.

**Comment by sissilab** [comment]
Hi, I have added some new features, including yours. See it: https://github.com/sissilab/obsidian-image-toolkit/releases.
