### ISSUE TITLE
 It is not possible to click on an image to open it in the editing state.

### ISSUE THREAD

**Issue by MILKMILKKING** [sissilab/obsidian-image-toolkit#31]
Since upgrading to OBSIDIAN version 0.13.9, it is not possible to click on an image to open it in the editing state.

**Comment by MILKMILKKING** [comment]
Even if I upgrade to obsidian 0.13.10, you can't open local images, but you can open web images in edit state.

**Comment by sissilab** [comment]
@MILKMILKKING 
I've upgraded my Obsidan to v0.13.14 (lastest version) and I haven't found this problem. 
You can try to upgrade Obsidan and this plug-in to the latest version.

**Comment by accept82** [comment]
I confirm v0.13.14 there are no problems with the image, everything opens perfectly and works, both on the old version of the plugin and on the new one!

**Comment by MILKMILKKING** [comment]
Thank you for your responses. I've upgraded to 0.13.14, but the problem still exists.
When I click on a local image in the editing state, the image disappears when the mouse clicks on it.
![XfoAzpuXNS](https://user-images.githubusercontent.com/69726213/147174207-4bbebcbb-e129-4b14-9c42-1665f928df52.gif)

**Comment by sissilab** [comment]
The problem was caused by the theme 'Blue Topaz'. If you have this probelm, plese see: 
https://github.com/sissilab/obsidian-image-toolkit/issues/24#issuecomment-1001336505
