### ISSUE TITLE
Incorrect operation of the setting to turn off the display of scaling on the image

### ISSUE THREAD

**Issue by accept82** [sissilab/obsidian-image-toolkit#32]
After closing Obsidian and restarting it, the setting for displaying the scaling value on the image continues to be enabled, although it is disabled in the plugin. Correct please
![23-12-2021_14-18_s11621](https://user-images.githubusercontent.com/90281362/147233465-1d391e6c-7e65-4871-a6dc-ada597d4f55c.png)
!

**Comment by sissilab** [comment]
@accept82  Sorry for the probelm. Please upgrade to v0.5.1.

**Comment by accept82** [comment]
I checked everything works fine thanks!
