### ISSUE TITLE
New version not working

### ISSUE THREAD

**Issue by dlccyes** [sissilab/obsidian-image-toolkit#33]
Just updated to v0.5.1, and it's not working. It wouldn't open when I click the image.

Rolling back to v0.4.2, and it works again.

😭😭

edit: doesn't work on Windows 10 & 11, but works on Kubuntu 21.10

**Comment by sissilab** [comment]
> 

Please show me the screenshot of the setting page, and your Obsidian's version.

**Comment by dlccyes** [comment]
Obsidian version: v0.13.14

screenshots of setting page: 
![image](https://user-images.githubusercontent.com/32875990/148159809-ca5e7ec1-cecb-41c6-a0ea-b141998df07c.png)  
![image](https://user-images.githubusercontent.com/32875990/148160165-5ea06f0f-b64e-4e78-86e3-9273f660892d.png)

I've disabled all the CSS snippets, changed to default theme, and also tried removing all other plugins, still won't work with v0.5.1

**Comment by sissilab** [comment]
@dlccyes  Hi, thanks for your information. It looks normal from your screenshots. 
It may be caused by some conflicts. You could:
1. reinstall the plugin.
2. change to the default theme.
3. disable all plugins except this plugin.
4. change current view to reading mode.

If you still have the problem after trying the above ways, please provide more details ( the gif/picture about the problem  ).

**Comment by benpla** [comment]
Same Effect on me. Screenshots looking same.
tryed:
 - disable all plugins, only enable image-toolkit: same behaviour
 - standard theme: same behaviour

The only thing I noticed: when all plugins are disabled, obsidian opens the image with a gray background when the mouse is clicked, not zoomed. This only happens as long as the mouse button is held down. The gray background is as big as the editor window. The image is centered in it.

Rollback: I have now copied the 3 files (manifest, rain and styles) from version 0.4.2 (https://github.com/sissilab/obsidian-image-toolkit/releases/tag/0.4.2) into the plugin directory: now everything works again as desired.

**Comment by sissilab** [comment]
@benpla  Thanks for your feedback. I've downloaded [v0.5.1](https://github.com/sissilab/obsidian-image-toolkit/releases/tag/0.5.1) to `.obsidian\plugins\obsidian-image-toolkit\`. But I still cannot find the problem you have. Please provide more details, such as gif/picture about the problem.

**Comment by dangquangvn** [comment]
I got the same issue.
Here some screenshorts:
![image](https://user-images.githubusercontent.com/61213745/149096263-003cbb74-de1b-4873-9085-13f038c600a4.png)
![image](https://user-images.githubusercontent.com/61213745/149096301-e0ca55c0-5658-4b4d-97b4-832acca31225.png)

**Comment by piojanu** [comment]
It didn't work for me too. However, WA for me is toggling all of these (see the screenshot) options. Then the plugin works.

![image](https://user-images.githubusercontent.com/23562932/151939792-4401f58e-d816-483f-abea-8eac4e65d2cd.png)

**Comment by sissilab** [comment]
@dlccyes @piojanu @benpla @dangquangvn 
Hi, the plugin has been upgraded to v1.0.1. You can try to upgrade to the lastest version.
If you still got the problem, you can try:
  1. uninstall it and then install it again
  2. create a new directory and open this directory with Obisidan, then install the plugin. (Test if it works)

Sorry for the problem you got! Welcome to give me a feedback after you upgrade it.

**Comment by mcnoat** [comment]
I encountered the same problem and it was solved by upgrading to version 1.0.1. Thanks, @sissilab!

**Comment by dlccyes** [comment]
v1.0.1 works on Windows 10 & 11! Thanks!
