### ISSUE TITLE
Modifier key to prevent misclicks

### ISSUE THREAD

**Issue by jorgb** [sissilab/obsidian-image-toolkit#36]
Sometimes I am just interested in the link of the picture I am seeing, or I click in the editor pane on a random place to start editing and the window with the image pops up. 

I would be more than happy if you could add a (configurable) modifier key to trigger the plugin. For example holding down shift or alt will show me the zoom icon over a picture, clicking at that point will trigger the enlarged picture. An enable / disable icon on the sidebar is also an option, as long as I can turn it off to prevent misclicks, but activate it when I need it. Alternatively, maybe rightclick, and tap in the menu that pops up there?

Another small request, shortcut arrow left and right to quickly go to the next image in the document? This is just nice to have though.

Anyway, thank you for this lovely plugin, I am an artist and being able to zoom and copy/paste is a livesaver.

**Comment by sissilab** [comment]
> Another small request, shortcut arrow left and right to quickly go to the next image in the document? This is just nice to have though.

Thanks for your feedback. The plugin has been upgraded to v1.0.1, and you can see all the images at the bottom of the popup layer and you can switch them. I'll think how to switch to the next/last image by arrow right/left. 

And I'll think about other requests you mentioned above.

**Comment by sissilab** [comment]
@jorgb Hi, you can set the hotkey for triggering an image in v1.3.1. If you set 'Ctrl', you cannot click an image to preview without holding 'Ctrl'. You can upgrade to the latest version and see if it's what you want.

![image](https://user-images.githubusercontent.com/82884158/172643215-ff9095bb-abe8-47b2-88e7-5c3e8868033c.png)

**Comment by jorgb** [comment]
Thanks I will try this!

**Comment by caoyirui** [comment]
Could you change the plugin so that you only show the zoom icon when holding down the modifier key? Otherwise, just show the default arrow.

**Comment by caoyirui** [comment]
> @jorgb Hi, you can set the hotkey for triggering an image in v1.3.1. If you set 'Ctrl', you cannot click an image to preview without holding 'Ctrl'. You can upgrade to the latest version and see if it's what you want.
> 
> ![image](https://user-images.githubusercontent.com/82884158/172643215-ff9095bb-abe8-47b2-88e7-5c3e8868033c.png)

Could you change the plugin so that you only show the zoom icon when holding down the modifier key? Otherwise, just show the default arrow.

**Comment by jorgb** [comment]
Thanks!
