### ISSUE TITLE
[Bug] Plugin opens the image as "invisible"

### ISSUE THREAD

**Issue by Signynt** [sissilab/obsidian-image-toolkit#38]
Sometime the plugin randomly stops working properly, I haven't been able to find what exactly causes this. I will try to click on an image to view it bigger, but nothing will happen. The image is "open", and I can no longer type any text or use keyboard shortcuts (I can open the command palette, but not type in it, and I can't use `Cmd + Q` to close Obsidian). This issue persists until I "close" the "open image" by hitting `esc`. I then have to restart Obsidian to be able to properly open the image with Image Toolkit. Then at some point the issue will randomly show up again.

**Comment by sissilab** [comment]
> I will try to click on an image to view it bigger, but nothing will happen. The image is "open", and I can no longer type any text or use keyboard shortcuts (I can open the command palette, but not type in it, and I can't use `Cmd + Q` to close Obsidian).

When the problem occurs, what's your Obsidian interface like on your screen? Did your Obsidan display something odd?
1. provide the plugin version
2. provide some screenshots when the problem occurs
3. open the Obsidian console (Ctrl+Shift+i) when the problem occurs and provide error logs

**Comment by Signynt** [comment]
Hey @sissilab, sorry for providing such little information, I was in a hurry while making the bug report yesterday.
I've been able to reproduce the bug in the help vault now, so you should be able to try it for yourself. (There are no errors reported by the console when the problem occurs)

**Steps to reproduce**:
1. Install Image Toolkit v1.0.1
2. Have multiple workspaces (Using the core plugin called "Workspaces")
3. Switch between workspaces
4. Try clicking on an image, the bug as I have described will occur.

**Comment by sissilab** [comment]
> * Switch between workspaces
> * Try clicking on an image, the bug as I have described will occur.

Thanks for your feedback, I'll work on it.

**Comment by sissilab** [comment]
@Signynt 
I've fixed this problem, please upgrade to v1.2.0.
