### ISSUE TITLE
Problems scrolling through photos with a dark background - they are not visible!

### ISSUE THREAD

**Issue by accept82** [sissilab/obsidian-image-toolkit#39]
There are problems with scrolling through photos with a dark background, it is very hard to see it

https://user-images.githubusercontent.com/90281362/153680680-7a980baa-bd0e-4983-8d9b-fa897e0de234.mp4

I suggest doing the following:
1. It is necessary to make it possible to choose the color of the substrate or make it permanent
Both light and dark backgrounds are combined very well on such a substrate.
![12 02 2022_01 32_s12528](https://user-images.githubusercontent.com/90281362/153680730-c3a0ca6d-6572-415f-87d8-53c5d045e2e2.png)

2. You need to make a stroke of the selected photo with a thin line (so that you can see which photo is currently active)
3. Make it possible in the settings to add arrows for scrolling through the photo
4. Add the ability to scroll through the photo from the keyboard left arrow and right arrow

I would be glad if you take this into account, thank you!

**Comment by cklaffer** [comment]
+1

**Comment by sissilab** [comment]
@accept82 @cklaffer 
Thanks for your feedback. I've taken them into account and published a new version. Please upgrade to v1.2.0.
