### ISSUE TITLE
更新到1.0.1之后点击图片会同时弹出预览和打开新的图片窗口

### ISSUE THREAD

**Issue by AiurArtanis** [sissilab/obsidian-image-toolkit#41]
@sissilab 

## 问题

在0.5.1版本下点击图片是这样的：
![image](https://user-images.githubusercontent.com/98091664/153806156-ba53aece-2dd0-4abd-9a10-cccfd36c50e9.png)
打开安全模式之后（关闭所有插件），ob默认的点击图片触发动作如下：
![image](https://user-images.githubusercontent.com/98091664/153806351-8aff733c-8a56-4424-801e-82e0082fa5b7.png)
升级到1.0.1之后点击图片会同时打开默认的图片窗口和toolkit自身的悬浮预览：
![image](https://user-images.githubusercontent.com/98091664/153806447-87eff390-2eb0-48f4-a916-ff900e412bcc.png)

希望增加`开关`用以控制预览图片时是否不再打开ob默认的图片窗口

## 环境

操作系统：win10
ob版本：v0.13.23
ob-image-toolkit版本：v0.5.1 → v1.0.1

**Comment by sissilab** [comment]
> 升级到1.0.1之后点击图片会同时打开默认的图片窗口和toolkit自身的悬浮预览：

请问默认的图片窗口 是什么意思？是主题自带图片功能？还是obsidian自带的？
这种如何可以复现。

**Comment by AiurArtanis** [comment]
> 请问默认的图片窗口 是什么意思？是主题自带图片功能？还是obsidian自带的？
> 这种如何可以复现。

抱歉，我建了个新库才发现这个问题不是必然复现的。然而我主库装的插件有点多，所以我得花点时间找到问题出自哪个插件/主题/碎片

**Comment by sissilab** [comment]
> 抱歉，我建了个新库才发现这个问题不是必然复现的。然而我主库装的插件有点多，所以我得花点时间找到问题出自哪个插件/主题/碎片

有时的确会有这种情况，重装或重建一个新库再装插件就能恢复了，如果后续还有问题，再看下
