### ISSUE TITLE
What tool do you use to show inputs in the first .gif file inside readme.md

### ISSUE THREAD

**Issue by Welding-Torch** [sissilab/obsidian-image-toolkit#42]
Hi, so this is not really an issue, more like a question of burning curiosity: What **tool** do you use to show inputs in the first .gif file inside readme.md. 

How do you make a .Gif like that? I really wanna know.

Thank you (and sorry for opening an issue for this question)

**Comment by sissilab** [comment]
> How do you make a .Gif like that? I really wanna know.

- [ScreenToGif](https://www.screentogif.com/): it can make gif
- [KeyCastOW ](https://brookhong.github.io/2014/04/28/keycast-on-windows.html#): it can show keystrokes
