### ISSUE TITLE
Image gallery shows broken image for block embeds

### ISSUE THREAD

**Issue by cansar** [sissilab/obsidian-image-toolkit#43]
How to reproduce:

Link to a section or block with with `![##Section Name]` and then open the gallery by clicking on an image on the page.

**Comment by sissilab** [comment]
> Link to a section or block with with `![##Section Name]` and then open the gallery by clicking on an image on the page.

Hi, I'm trying to reproduce your problem.
There is a section ` [[### 6. Buy me a coffee]]`. When your mouse is over the section in the reading mode, the content of this section  will be displayed and the image in this section cannot be clicked to preview on the popup layer.

![image](https://user-images.githubusercontent.com/82884158/154596958-13d86abd-99ed-4009-a91d-850c149eff3c.png)

**Comment by cansar** [comment]
Sorry, I should've provided more details. The key is embedding, not linking. Here's an example screenshot and markdown. I'm using 2 images (the same image twice) but one image is enough to trigger, it's just easier to see with two. Note the missing preview image between the other 2:
<img width="877" alt="image" src="https://user-images.githubusercontent.com/92989/154750550-822fe2f7-8e4a-4cf4-81cf-bcb6c61110d3.png">

`![[Pasted image 20220218113442.png]]

Example text ^db5194

![[#^db5194]]

![[Pasted image 20220218113442.png]]
`

**Comment by sissilab** [comment]
@cansar  
I've fixed the problem, please upgrade to v1.2.0.
Thanks for your feedback.
