### ISSUE TITLE
Snap zoom to 100%

### ISSUE THREAD

**Issue by Onurtag** [sissilab/obsidian-image-toolkit#45]
It would be great to have a snap to 100% zoom feature on this extension.
Basically going from 95% -> 104.5% zoom it goes 95% -> 100% and vice versa.

I have the code and its working but I didn't want to open a pull request yet as you might want to add an option to the options menu or something.
https://github.com/Onurtag/obsidian-image-toolkit/commit/d22fb3f2b9ddc978d38572c245aaa91affc7e012

Thanks for the great work on obsidian image toolkit.

**Comment by sissilab** [comment]
@Onurtag 
Thanks for your suggestion. I've taken it into account, and in addition, I've added 'zoom to 100%' on the toolbar. Plase upgrade to v1.2.0.
