### ISSUE TITLE
[feature request]: Do not obscure what are editing.

### ISSUE THREAD

**Issue by cnlinxi** [sissilab/obsidian-image-toolkit#47]
At present, if you click the text behind, the picture will disappear automatically after clicking the image.
Can this toolkit displays a picture without blocking the contents behind it?

**Comment by sissilab** [comment]
> At present, if you click the text behind, the picture will disappear automatically after clicking the image. Can this toolkit displays a picture without blocking the contents behind it?

Hi, are there two requests you commented?
1. At present, if you click the text behind, the picture will disappear automatically after clicking the image.
--> Please check and provide your themes, or othere image-related plugins. If you can provide screenshots or a recording video, that'll be greate.
2. Can this toolkit displays a picture without blocking the contents behind it?
--> When you click a picture, the picture will be previewed on the popup layer. Did you mean that you wanna remove the popup layer?

**Comment by sissilab** [comment]
@cnlinxi  Hi, please upgrade to v1.3.1 and turn on 'Pin an image' to open pin mode. In that mode, you can preview the popped image and edit your notes at the same time.

![image](https://user-images.githubusercontent.com/82884158/172641907-29a888c7-2087-406d-ab1e-877aa2a32d1b.png)
