### ISSUE TITLE
Viewing an image in full screen mode

### ISSUE THREAD

**Issue by accept82** [sissilab/obsidian-image-toolkit#5]
Good day! Could you make a setting in which it would be possible to view the photo (image) in full screen mode. That is, when you click a photo, the photo (image) is enlarged to full screen mode.
![07-09-2021_22-11_s6050](https://user-images.githubusercontent.com/90281362/132398757-2ffb413c-386c-4e7a-a194-d1fe3aee166a.gif)

**Comment by sissilab** [comment]
Hi, the full-screen mode has been added.
https://github.com/sissilab/obsidian-image-toolkit/releases/tag/0.3.5

**Comment by accept82** [comment]
Добрый день, Спасибо проверил! Обнаружил небольшие проблемы:
1. если есть панель windows и открыть фото в полноэкранном режиме с право есть большой зазор - можно ли как-то сделать чтобы небыло зазоров и фото открывалось на полный экран .В идеале чтобы закрывало панель windows как показано на фото gif?
![08-09-2021_12-31_s6060](https://user-images.githubusercontent.com/90281362/132485396-6f19d9cd-82d1-4528-b3c9-ce118b103ea8.png)

2. В полноэкранном режиме пропадает курсор - это не очень удобно, можно ли этот курсор  вернуть назад?

**Comment by accept82** [comment]
It would also be nice to add the ability to exit full-screen mode with a cross on the right of the screen or with the Close label. When you clicked on the cross or Close, the window was completely closed as by ESC

**Comment by sissilab** [comment]
> Good afternoon, Thanks checked! Found small problems:
> 
> 1. if there is a windows panel and open the photo in full screen mode with the right there is a large gap - is it possible to somehow do so that there are no gaps and the photo opens in full screen. Ideally, to close the windows panel as shown in the gif photo?
>    ![08-09-2021_12-31_s6060](https://user-images.githubusercontent.com/90281362/132485396-6f19d9cd-82d1-4528-b3c9-ce118b103ea8.png)
> 2. In full-screen mode, the cursor disappears - this is not very convenient, can this cursor be returned back?

Sorry for late reply. 
1) Q: The image has no gaps in full-screen mode. ==> A: The image is enlarged proportionally (fit mode), so there're gaps. 
Fill and stretch modes will take up entire screen. I have no idea if you want these modes. (By the way, you can see wallpaper setting in Windows OS, if you're confused about fit, fill, and stretch modes.) 
2) Q: The cursor disappears in full-screen mode. ==> A: The intent of design about full-screen mode is just viewing an image without any other opeations.

**Comment by sissilab** [comment]
> It would also be nice to add the ability to exit full-screen mode with a cross on the right of the screen or with the Close label. When you clicked on the cross or Close, the window was completely closed as by ESC

You can press Esc or click by mouse to exit full-screen mode.

**Comment by accept82** [comment]
> > Добрый день, спасибо проверено! Обнаружил небольшие проблемы:
> > 
> > 1. если есть панель windows и открывать фото в полноэкранном режиме с правой есть большой пробел - можно ли как-то сделать так, чтобы не было пробелов и фото открывалось во весь экран. В идеале закрыть панель окон как показано на гифке фото?
> >    ![08-09-2021_12-31_s6060](https://user-images.githubusercontent.com/90281362/132485396-6f19d9cd-82d1-4528-b3c9-ce118b103ea8.png)
> > 2. В полноэкранном режиме курсор пропадает - это не очень удобно, можно ли вернуть этот курсор обратно?
> 
> Извините за поздний ответ.
> 
> 1. В: В полноэкранном режиме изображение не имеет пропусков. ==> A: Изображение увеличено пропорционально (режим подгонки), поэтому есть пробелы. 
>    Режимы заполнения и растяжения занимают весь экран. Не знаю, нужны ли вам эти режимы. (Кстати, вы можете увидеть настройку обоев в ОС Windows, если вас не устраивают режимы подгонки, заливки и растяжения.)
> 2. В: Курсор исчезает в полноэкранном режиме. ==> A: Полноэкранный режим предназначен для того, чтобы пользователи могли просто просматривать изображение без каких-либо других операций.

Good day! In my opinion, there should be a cursor in fullscreen mode! See how it works in ShareX and it's very nice. I also want to note that in full screen mode, you are left with the Windows control panel, which is not very good - the meaning of full screen mode is lost. Please implement the ability to view the image in full screen mode over the Windows panel

**Comment by sissilab** [comment]
Hi, I have added a cursor in full-screen mode.
Please update v0.4.0: https://github.com/sissilab/obsidian-image-toolkit/releases/tag/0.4.0.
As to real full-screen mode without Windows taskbar, I'll work on that.

**Comment by accept82** [comment]
Good evening! I checked everything with update 0.4.0 - beyond praise - this is a really very useful plugin. Thank you very much for your work! If you add full screen mode, there will be fire at all!
