### ISSUE TITLE
FR: Give a count of Images in the Gallery Navbar

### ISSUE THREAD

**Issue by ManasMadrecha** [sissilab/obsidian-image-toolkit#52]
Show a count of number of images embedded in the current markdown page.

**Comment by sissilab** [comment]
> Show a count of number of images embedded in the current markdown page.

Hi, please upgrade to v1.3.1 to see it.

![image](https://user-images.githubusercontent.com/82884158/172596679-bbc506a1-f2e4-4bc6-a1ef-a5472fb18784.png)
