### ISSUE TITLE
FR: Give option to drag the Image modal here & there, instead of always obscuring the text behind

### ISSUE THREAD

**Issue by ManasMadrecha** [sissilab/obsidian-image-toolkit#53]
Currently, the image popover takes over the entire screen. It would be nice to have an option to move the image popover aside, and thus, we can concurrently type as well as see the image.

**Comment by sissilab** [comment]
@ManasMadrecha Hi, it has added 'pin mode' in the latest version. To be able to use this mode, you need to turn on 'Pin an image' on the plugin setting page.  It's allowed to preview the popped image and edit your notes at the same time. You can upgrade to v1.3.1 and have a try.

![image](https://user-images.githubusercontent.com/82884158/172640724-bd333e2f-18d7-4e27-ae93-9510fe9ca600.png)
