### ISSUE TITLE
BUG: 1.2版本没有图片复制功能

### ISSUE THREAD

**Issue by YIRU69** [sissilab/obsidian-image-toolkit#55]
如题
插件1.2版本的图片复制功能没有的，不知是否是我个人的原因
我回退了1.0.1版本就有了
如果是bug希望能修复一下

**Comment by sissilab** [comment]
@YIRU69  不好意思，已在v1.2.1中恢复“复制”图标按钮。

**Comment by YIRU69** [comment]
万分感谢！
