### ISSUE TITLE
希望能有左右翻页的按钮，临近的图标就可以 快速查看了，像gallery一样

### ISSUE THREAD

**Issue by chibincode** [sissilab/obsidian-image-toolkit#56]
希望能有左右翻页的按钮，临近的图标就可以 快速查看了，像gallery一样
-
I hope there are left and right page-turning buttons and the adjacent icons can be viewed quickly, just like a gallery

**Comment by sissilab** [comment]
> ## 希望能有左右翻页的按钮，临近的图标就可以 快速查看了，像gallery一样

目前可以进入 Image Toolkit 设置界面，开启如下图设置，可通过 组合键+左右键 或 直接点击最下方的图片进行切换。
![image](https://user-images.githubusercontent.com/82884158/168424312-cbc4aa1b-9f04-4171-9581-c2687b86bdb5.png)

**Comment by chibincode** [comment]
收到，谢谢！

sissilab ***@***.***> 于2022年5月14日周六 19:50写道：
