### ISSUE TITLE
Poor to viewing SVG with transparent background 

### ISSUE THREAD

**Issue by SSkyang** [sissilab/obsidian-image-toolkit#57]
![image](https://user-images.githubusercontent.com/12947895/165718049-ef71a361-860c-461d-9afe-b33a59f9e9cf.png)
=> preview
![image](https://user-images.githubusercontent.com/12947895/165718068-11298ad9-de92-471d-9165-d7046d8d66e4.png)

**Comment by sissilab** [comment]
@SSkyang  
The popup layer is transparent, too. I'll work on it and provide background color setting of the popup layer.

**Comment by sissilab** [comment]
@SSkyang Hi, it has been solved in v1.3.1. There will be a default white background color for the image with transparent background, and the background color can be set on the plugin settings page. You can upgrade to v1.3.1 and see how it works. out

![image](https://user-images.githubusercontent.com/82884158/172638182-8071a9fd-1b91-41dc-880e-5a361842f587.png)

**Comment by SSkyang** [comment]
Thank you so much!
