### ISSUE TITLE
Copy Image button gone from image view pane

### ISSUE THREAD

**Issue by antoninbrthn** [sissilab/obsidian-image-toolkit#58]
After updating to 1.2.0, it seems like the "Copy Image" button as disappeared from the navigation bar:
<img width="623" alt="Screenshot 2022-04-29 at 13 24 54" src="https://user-images.githubusercontent.com/23316135/165943843-a8f92846-bdcd-4b46-b089-8d2e8640e869.png">

Thanks a lot for your great work, this is my favorite Obsidian package and a game changer for working with images.

**Comment by sissilab** [comment]
> After updating to 1.2.0, it seems like the "Copy Image" button as disappeared from the navigation bar:

The "Copy Image" button cannot copy the changed image, so it was removed in the lastest version.
If you feel it's useful for you, I'll recover it.

**Comment by antoninbrthn** [comment]
I found it really useful indeed, since there does not seem to be any other convenient way to copy the image directly from Obsidian when using this plug-in (for example, drag-and-drop copies only the link to Obsidian instead of the image itself).
Many thanks again for your work!

**Comment by nousernameavailableanymore** [comment]
The "copy" button is one of the core/integral features of the plugin.
In Live Preview, there is no other efficient way to copy an image from a codeblock (for example when using image grids via admonitions).

So I do not know which features were traded in for the "copy" button in 1.2.0 but it was definitely **NOT** worth it.

I reverted back to the previous version and will stay there until the copy button is back, as my whole workflow breaks without it.
If this is the last version to feature the button, then this will have been the last version of the plugin which I will be using from now on.

Btw:
removing core features from any kind of software without huge warning messages is not really best practice.
However, the plugin itself is awesome and adds a ton of value to obsidian.
So I really hope the "copy" button will make a triumphant return soon.

**Comment by sissilab** [comment]
@antoninbrthn  @nousernameavailableanymore 
It has been recovered in the latest version v1.2.1.

**Comment by nousernameavailableanymore** [comment]
Thank you.
