### ISSUE TITLE
Unresponsive Images

### ISSUE THREAD

**Issue by micwaab** [sissilab/obsidian-image-toolkit#59]
When this plugin works, it's 100% amazing—a lifesaver. Unfortunately, I have been experiencing an issue repeatedly. 

While sometimes it works as it's meant to, other times an image does not enter the Toolkit mode and simply returns to the standard Obsidian page view after a brief enlargement (which only lasts as long as the mouse click is held.)

**Comment by sissilab** [comment]
> While sometimes it works as it's meant to, other times an image does not enter the Toolkit mode and simply returns to the standard Obsidian page view after a brief enlargement (which only lasts as long as the mouse click is held.)

It may be caused by your theme. Please tell me your theme, and you can try to switch to the default theme.

**Comment by HiWQ** [comment]
Minimal theme Fails
+1

**Comment by sissilab** [comment]
@micwaab  @HiWQ 
You can install 'Style Settings' plugin, and turn on 'Disable image zoom'.
![image](https://user-images.githubusercontent.com/82884158/167593834-56794900-0137-4780-8b62-8a14181af5c5.png)

**Comment by micwaab** [comment]
@sissilab Thank You!
