### ISSUE TITLE
[REQUEST] Disable plugin for images that are also links

### ISSUE THREAD

**Issue by firinael** [sissilab/obsidian-image-toolkit#6]
Clicking images in the Community Plugins browser to go to the github or something like that will open the image, and that's probably not a behaviour most users desire.

**Comment by sissilab** [comment]
> Clicking images in the Community Plugins browser to go to the github or something like that will open the image, and that's probably not a behaviour most users desire.

Thanks for your feedback. I'll limit image to be clicked everywhere.

**Comment by accept82** [comment]
I fully support, there is a problem! A link with a photo opens in the browser and at the same time the photo in Obsidian is enlarged, this is not very convenient and very annoying!

**Comment by sissilab** [comment]
> I fully support, there is a problem! A link with a photo opens in the browser and at the same time the photo in Obsidian is enlarged, this is not very convenient and very annoying!

The markdown about  'A link with a photo': 
```html
[ ![Engelbart](https://history-computer.com/ModernComputer/Basis/images/Engelbart.jpg) ](https://bing.com/)
```

You just want to click the photo to open the url in the browser, but now, the photo will be enlarged on the popup layer too?
Is this what you mean?

**Comment by sissilab** [comment]
> I fully support, there is a problem! A link with a photo opens in the browser and at the same time the photo in Obsidian is enlarged, this is not very convenient and very annoying!

I understand now. Thank you very much for your feedback. I'll work on that.

**Comment by sissilab** [comment]
Hi, I have canceled clicking a picture with a link.
Please update v0.4.0: https://github.com/sissilab/obsidian-image-toolkit/releases/tag/0.4.0.
