### ISSUE TITLE
"Copy" has disappeared

### ISSUE THREAD

**Issue by OnkelTem** [sissilab/obsidian-image-toolkit#61]
I installed this plugin only because I needed the copy button. But today I see it's just disappeared. What the...

![image](https://user-images.githubusercontent.com/114060/167895532-d218a4de-685d-4586-86f6-46ab92e92c6b.png)

Version: 1.2.0
Obsidian version: 0.14.6

**Comment by sissilab** [comment]
@OnkelTem 
Sorry for the inconvenience! It has been recovered in the latest version v1.2.1.
