### ISSUE TITLE
希望能用快捷键开启或关闭插件

### ISSUE THREAD

**Issue by ss818** [sissilab/obsidian-image-toolkit#63]
希望能够用快捷键开启或关闭弹出图片，有时候弹出图片会是干扰。

**Comment by sissilab** [comment]
> 希望能够用快捷键开启或关闭弹出图片，有时候弹出图片会是干扰。

是否指：有时点击图片不需要弹出来预览图片，希望限制下，比如 当按住 Ctrl 时，点击图片才弹出预览，直接鼠标点击图片，不弹出预览。

**Comment by ss818** [comment]
是这样的，按住ctrl再开启是更好的模式，因为现在阅读笔记的时候经常会把图片点出来，影响体验。

**Comment by sissilab** [comment]
@ss818  Hi、已在 v1.3.1 实现该功能，可以在插件配置界面进行配置。

![image](https://user-images.githubusercontent.com/82884158/172597658-bd19e9eb-267d-48f9-94d4-d1ab8a3917c0.png)

**Comment by ss818** [comment]
十分感谢！


祝万事如意



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月8日(周三) 晚上6:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [sissilab/obsidian-image-toolkit] 希望能用快捷键开启或关闭插件 (Issue #63)




 
@ss818  Hi、已在 v1.3.1 实现该功能，可以在插件配置界面进行配置。
