### ISSUE TITLE
Add the ability for the plugin to work in separate windows from the program in the release : v0.15.3

### ISSUE THREAD

**Issue by accept82** [sissilab/obsidian-image-toolkit#64]
0.15 added the ability to open notes in a separate window. Please add the ability for the plugin to work in these separate windows. Because it doesn't work with your plugin at the moment

**Comment by Xieleilab** [comment]
confirm, same request

**Comment by icytree** [comment]
+1

**Comment by elrindir** [comment]
+1 Doesn't work in notes in seperate window.

**Comment by sissilab** [comment]
@accept82  @Xieleilab @icytree @elrindir Thanks for your support. This feature has supported in v1.4.0.
