### ISSUE TITLE
[Bug] Only works on image files, not notes with images alongside them

### ISSUE THREAD

**Issue by t3dium** [sissilab/obsidian-image-toolkit#69]
The plugin only works on individual image files and not images which are placed alongside notes.

Obisidan: latest version
OS: windows & linux

**Comment by sissilab** [comment]
> but the plugin only works on individual image files and not images which are placed alongside notes.

@t3dium  Thanks for the feedback. You mentioned that images could be placed alongside nodes. I wonder how to reproduce it.

**Comment by sissilab** [comment]
@t3dium  Could you please provide more information about your problem.
