### ISSUE TITLE
[SUGGESTION] Add a `max-height` property to the displayed image, or a background to the toolbar

### ISSUE THREAD

**Issue by firinael** [sissilab/obsidian-image-toolkit#7]
When clicked on, the image can be displayed on top of the toolbar controls. This renders the controls unusable, and by no fault of the user.

Please either limit the image height or do something like adding a background to the toolbar.

**Comment by sissilab** [comment]
> When clicked on, the image can be displayed on top of the toolbar controls. This renders the controls unusable, and by no fault of the user.
> 
> Please either limit the image height or do something like adding a background to the toolbar.

Did you mean that the top toolbar won't be covered by the popup layer?
And the scope of the popup layer is blue background areas of following image.
![obsidian_page](https://user-images.githubusercontent.com/82884158/132985627-f5356f07-3dfe-413c-92fe-877262b32fdf.png)

**Comment by sissilab** [comment]
Hi, I have added a background color for the bottom toolbar.
Please update v0.4.0: https://github.com/sissilab/obsidian-image-toolkit/releases/tag/0.4.0.

Thanks for your suggestion.
