### ISSUE TITLE
Not work after clicking （No preview）

### ISSUE THREAD

**Issue by vin-zhou** [sissilab/obsidian-image-toolkit#70]
Hi @sissilab ，I'm a new user of obsidian. 
Reproduce steps： 
1.  I  download https://github.com/cyddgh/obsidian-out-of-the-box, which contain image toolkit.
2.  Add an image to markdown file
3. Single click the image, no preview show（Maybe just a flash, but I can't see). 
4. Try to turn off other plugins, still not work.

Thank you for your any response!

**Comment by sissilab** [comment]
@vin-zhou  Hi, there is a confict between the theme () and image-toolkit plugin while clicking an image. It will work after you turn off image zoom of the theme.

You can solve it as follows:
1. Enter ‘Style Settings’
2. find 'Blue Topaz Theme / 2.Detail Settings / 2.3. Element Style'
3. turn on 'Mute zoom into the image on click'

BTW, suggest to upgrade to the latest version

**Comment by vin-zhou** [comment]
@sissilab  Problem solved!  Thank you very much for your help and your work! This image toolkit is great!

**Comment by jiyee** [comment]
> @vin-zhou Hi, there is a confict between the theme (Blue Topaz) and image-toolkit plugin while clicking an image. It will work after you turn off image zoom of the theme.
> 
> You can solve it as follows:
> 
> 1. Enter ‘Style Settings’
> 2. find 'Blue Topaz Theme / 2.Detail Settings / 2.3. Element Style'
> 3. turn on 'Mute zoom into the image on click'
> 
> BTW, you could enjoy the up-to-date features through upgrading to the latest version.

建议这个注意事项放到 README 里，我也困惑了好久才发现这里的冲突。大部分人可能不容易找到这个 issue。
