### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by jerviscui** [sissilab/obsidian-image-toolkit#73]
Block reference was mistakenly thought to be a picture.

The code:
![image](https://user-images.githubusercontent.com/6396748/196490773-7922d7fd-d548-4316-9a31-b3392240f9c1.png)

In box:
![image](https://user-images.githubusercontent.com/6396748/196490664-a486ea2f-da39-43dc-9fbf-42cc588af16c.png)

**Comment by sissilab** [comment]
fixed in v1.4.1.
