### ISSUE TITLE
The plugin is working only for notes opened in main window

### ISSUE THREAD

**Issue by sohanglal** [sissilab/obsidian-image-toolkit#75]
The plugin is working only for notes opened the in the main obsidian window and not for notes opened in a new window
Also, thanks for making such an amazing plugin!

**Comment by accept82** [comment]
I also support the idea of ​​making the plugin work in a separate window.!
I hope that the developer is doing well and he will return to duty! Unfortunately, at the moment the plugin has not been updated for 8 months.

**Comment by sissilab** [comment]
same as #64

**Comment by sissilab** [comment]
@sohanglal This feature has been supported in v1.4.0.

**Comment by accept82** [comment]
sissilab, Greetings! You have not been for a long time, I am glad that you would come back to us and thank you very much for your work, it really helped me!

**Comment by sissilab** [comment]
> sissilab, Greetings! You have not been for a long time, I am glad that you would come back to us and thank you very much for your work, it really helped me!

Thanks a lot, I really appreciate it. I've been busy those days and now things go back to normal. I'll take the effort to improve the plug-in.

**Comment by sohanglal** [comment]
> @sohanglal This feature has been supported in v1.4.0.

Thanks a lot for the implementation! It is working perfectly well!
