### ISSUE TITLE
The list view is weird

### ISSUE THREAD

**Issue by khaled-magdy123** [sissilab/obsidian-image-toolkit#82]
the list view is weird, any idea how to solve this?

![image](https://github.com/sissilab/obsidian-image-toolkit/assets/93298421/53b90c6f-242c-4440-a430-e42f99af8045)

**Comment by sissilab** [comment]
> the list view is weird, any idea how to solve this?

It looks irrelevant with this plugin. I'm closing it now. If you got any questions about this plugin, your feedback is welcome.
