### ISSUE TITLE
Please support pictures in full-screen mode and support mouse click buttons to navigate left and right to the next picture

### ISSUE THREAD

**Issue by zhouxinghong** [sissilab/obsidian-image-toolkit#86]
Please support pictures in full-screen mode and support mouse click buttons to navigate left and right to the next picture
For example:
![image](https://github.com/sissilab/obsidian-image-toolkit/assets/54253524/163bc2cd-d0e9-4d90-ac5d-c48e79c9be1b)![image](https://github.com/sissilab/obsidian-image-toolkit/assets/54253524/ad08be06-e5c5-45b3-adf5-4f8e2b882cbe)
Currently there is no such function in the latest version, it is very inconvenient to use, I hope it can be added.
There is no such function in the latest version at present, it is very inconvenient for users who like to use the mouse to navigate, hope it can be added.

Also found two errors:
1. When I turn off the navigation thumbnails at the bottom, the left and right arrow key navigation doesn't work anymore.

2. After closing the navigation thumbnail at the bottom, the length and width of the pop-up image should increase, but the actual situation is that the length and width of the pop-up image have not increased. Please fix this bug, thank you very much!

Thank you for the very good image extension 👍😜

請支持圖片全屏模式下支持鼠標點擊按鈕進行左右導航到下一張
例如：
![image](https://github.com/sissilab/obsidian-image-toolkit/assets/54253524/163bc2cd-d0e9-4d90-ac5d-c48e79c9be1b)![image](https://github.com/sissilab/obsidian-image-toolkit/assets/54253524/ad08be06-e5c5-45b3-adf5-4f8e2b882cbe)
目前最新版本中沒有這個功能，對於喜歡使用鼠標來導航的用戶來說使用起來非常不方便，希望可以加入它。

另外發現二個錯誤：
1. 當我關閉底部的導航縮略圖後，左右方向鍵導航不起作用了。

2. 關閉底部的導航縮略圖後，彈出圖片的長寬尺寸應該增大才對，但是實際的情況是彈出圖片的長寬尺寸沒有增大。請修復這個錯誤，非常感謝您！

感謝您提供的非常優秀的圖像擴展👍😜

**Comment by sissilab** [comment]
> 1. When I turn off the navigation thumbnails at the bottom, the left and right arrow key navigation doesn't work anymore.
> 2. After closing the navigation thumbnail at the bottom, the length and width of the pop-up image should increase, but the actual situation is that the length and width of the pop-up image have not increased. Please fix this bug, thank you very much!

When closing gallery navbar (navigation thumbnails at the bottom):
1. it'll stop parsing all images, which will cause the fact that images cannot be switched.
2. the image will be scaled based on some factors but not simply zoomed in. The zoom mechanism may be needed to optimize. It's so great if you could provide some sample images.

**Comment by zhouxinghong** [comment]
Hello! Please add left and right navigation action buttons to the image
OS: Win10
Obsidian: 1.4.13
The effect is as follows:
![image](https://github.com/sissilab/obsidian-image-toolkit/assets/54253524/913fd08a-b31a-40d9-a4e4-fbb225a90974)
