### ISSUE TITLE
Cannot view resized table images in gallery view

### ISSUE THREAD

**Issue by erik-buchholz** [sissilab/obsidian-image-toolkit#88]
If you resize an image in a table, you need to [escape the vertical bar.](https://help.obsidian.md/Editing+and+formatting/Advanced+formatting+syntax)
I.e., `![[Pasted image 20230817120904.png|300]]` becomes `![[Pasted image 20230817120904.png \|300]]`.
 
Now, any images resized using the escaped vertical bar will not be displayed in the Gallery bar, i.e., it is impossible to switch over images in a table. This prevents the comparison of images displayed side-by-side with a table in the enlarged view.

Minimal working example:
```
![[cat1.png]]


| A | B | C |
| --- | --- | --- |
| ![[cat2.png]] | ![[cat3.png \|300]] | ![[cat4.png \|300]] |

![[cat5.png]]
```

In the example, you will be able to navigate to cat1, 2, and 5 in the gallery, but not to cats 3 and 4. It is possible to enlarge cats 3 and 4, but once you navigated to another cat, you cannot go back. 

Images are attached. 

![image](https://github.com/sissilab/obsidian-image-toolkit/assets/61317214/7649d74a-f403-489d-9dd4-bd3a0b5c801f)

Thanks for the amazing plug-in! If you need help implementing this, I am happy to do so. But as I have never used TypeScript before, I might need some guidance on what you think where the problem lies or where to start looking. :)

**Comment by sissilab** [comment]
fixed in v1.4.1.
