### ISSUE TITLE
Copy text with image from a note

### ISSUE THREAD

**Issue by Andy-AO** [sissilab/obsidian-image-toolkit#89]
Can it be achieved to copy text and images together from notes? Currently, Obsidian does not implement this feature, which makes it very difficult to copy images and text from text.

# links
- [Copy image from a note - Feature requests - Obsidian Forum](https://forum.obsidian.md/t/copy-image-from-a-note/2318)

**Comment by sissilab** [comment]
> Can it be achieved to copy text and images together from notes?

Hi, this plugin is focussing on image itsellf operations. As to the feature of 'Copy', it's able to support to copy an image, but not context texts of that image.
