### ISSUE TITLE
Could you please turn off the function of enlarging the picture that comes with Obsidian when you click to preview the picture? It would be conflicting

### ISSUE THREAD

**Issue by AHUIc** [sissilab/obsidian-image-toolkit#93]

**Comment by sissilab** [comment]
Could you find out where the conflict of enlarging the picture actually comes from? 
from some plugins? from a theme?

Please provide more details about the conflict, e.g. screenshot, theme, plugins, Obsidian version, ...

**Comment by AHUIc** [comment]
In real-time preview mode, when you click an Image, the image will be enlarged. Then, the image preview function of the Image Toolkit is enabled. Can I turn off the click to enlarge feature that comes with Live Preview mode

**Comment by lucmos** [comment]
Hello, 

@sissilab it is a feature of the minimal theme, here an example of the behaviour:

https://github.com/sissilab/obsidian-image-toolkit/assets/11019190/3dd59eef-f8c3-4d6c-9d61-45a5fa1be632

After some searching, I managed to disable the click-to-zoom feature in this way: https://github.com/kepano/obsidian-minimal/issues/41#issuecomment-971821526
