### ISSUE TITLE
Image cannot open when cursor is 'release' outside preview image

### ISSUE THREAD

**Issue by leonasdev** [sissilab/obsidian-image-toolkit#96]
looks like it becomes preview image of default obsidian when cursor is release outside preview image.

https://github.com/sissilab/obsidian-image-toolkit/assets/39915562/2487cb12-8ded-4439-b17d-350b99c68f75

**Comment by sissilab** [comment]
> looks like it becomes preview image of default obsidian when cursor is release outside preview image.
It seems influenced by your theme. So what's your theme?
If it really matters with your theme, you can try to close image zooming function of the theme  by `Style Settings` plugin.

**Comment by leonasdev** [comment]
> > looks like it becomes preview image of default obsidian when cursor is release outside preview image.
> 
> It seems influenced by your theme. So what's your theme? If it really matters with your theme, you can try to close image zooming function of the theme by `Style Settings` plugin.

Wow, it's really affect by theme.

I use `Minimal` theme, and it's works normally after I toggle the `Disable image zoom` via `Style Settings` plugin.

Thank you! @sissilab
